name: 'Mongo Export'
description: 'Export json to mongo db collection'

inputs:
  uri:
    description: 'The URI of the server without username and password'
    required: true
  export:
    description: 'Json file path'
    required: true
  db:
    description: 'Name of the db'
    required: true
  collection:
    description: 'Name of the collection'
    required: true
  should_rewrite:
    description: 'Should rewrite data'
    type: boolean
    required: = true
  
runs:
  using: 'node16'
  main: 'index.js'